return {
    monitor = awesome_performer_assets_path .. '/icons/monitor.png',
    audio_general = awesome_performer_assets_path .. '/icons/audio_general.png',
    audio_alsa = awesome_performer_assets_path .. '/icons/audio_general.png',
    audio_bluetooth = awesome_performer_assets_path .. '/icons/audio_bluetooth.png',
    audio_bluez = awesome_performer_assets_path .. '/icons/audio_bluetooth.png',
    monitor_connected = awesome_performer_assets_path .. '/icons/monitor-connected.png',
    monitor_disconnected = awesome_performer_assets_path .. '/icons/monitor-disconnected.png',
    gitlab = awesome_performer_assets_path .. '/icons/gitlab-orange-on-dark.png',
    sleep = awesome_performer_assets_path .. '/icons/sleep.png',
    hibernate = awesome_performer_assets_path .. '/icons/hibernate.png',
    focus_mode_on_icon = awesome_performer_assets_path .. '/icons/focus-mode-on.png',
    focus_mode_off_icon = awesome_performer_assets_path .. '/icons/focus-mode-off.png',
    mail_personal = awesome_performer_assets_path .. '/icons/mail-personal.png',
    mail_work_1 = awesome_performer_assets_path .. '/icons/mail-work-1.png',
    mail_work_2 = awesome_performer_assets_path .. '/icons/mail-work-2.png',
    systray_delimeter_left = awesome_performer_assets_path .. '/icons/systray-delimeter-left.png',
    systray_delimeter_right = awesome_performer_assets_path .. '/icons/systray-delimeter-right.png',
}
